### ISSUE TITLE
Synology Drive version 3.2.1-13271

### ISSUE THREAD

**Issue by jaroslavresler** [flathub/com.synology.SynologyDrive#30]
The current version of the Synology Drive client is 3.2.1-13271, the version provided by flathub remains still 3.1.0. Would it be possible to update package to the latest version? Thanks a lot.
Jaroslav

**Comment by 9thdude** [comment]
Currently testing the upgrade in #31 and I'm unable to run it on Fedora 37 via Wayland. When I attempt to run it via terminal, I get the following output:
`Qt: Session management error: None of the authentication protocols specified are supported
debug.message: Cannot find path by key "user_cloud_station_app_path"
debug.message: Cannot find path by key "user_cloud_station_data_path"
debug.message: Cannot find path by key "user_cloud_station_working_dir_path"
debug.message: Cannot find path by key "user_cloud_station_drive_ui_path"
Gtk-Message: 14:38:58.404: Failed to load module "xapp-gtk3-module"
Gtk-Message: 14:38:58.424: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:38:58.424: Failed to load module "pk-gtk-module"
Gtk-Message: 14:38:58.424: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:38:58.424: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported`

Not sure if this is a Fedora, Wayland, or Gnome issue; if it is, let me know where the problem is and I'll take it to the respective owners.

**Comment by lil5** [comment]
These "errors" show up when it does work as well, maybe it's something else...

As you are running gnome are you using the app indicator extension? I've read of more people who say it's now working while it is just opened up an indicator only.

**Comment by 9thdude** [comment]
> @9thdude These "errors" show up when it does work as well, maybe it's something else...
> 
> As you are running gnome are you using the app indicator extension? I've read of more people who say it's now working while it is just opened up an indicator only.
> 
> I'll try testing this on Fedora gnome wayland as well to see if I can reproduce.

I am on GNOME using the AppIndicator and KStatusNotifierItem extension with everything up to date. If there's some specific troubleshooting you would like for me to try, I'd be happy to help.

**Comment by lil5** [comment]
@9thdude My co-maintainer has already closed this issue but has it been fixed for you since the updated version? Specifically version v3.2.1

**Comment by lil5** [comment]
I've tested SynologyDrive on a clean install of Fedora SilverBlue 37 with App indicators extension, inside GNOME Boxes. And it works fine even with another application using the app indicator as well.

What I've tested;
- login
- sync from nas
- close and open settings to/from the app indicator

**Comment by lil5** [comment]
@9thdude That sounds like an application issue, please pass this on to the Synology team. 
As for this issue I'm closing it as it doesn't seem to have anything to do with flatpak packaging.

**Comment by lisyclover** [comment]
> @9thdude That sounds like an application issue, please pass this on to the Synology team.

After deleting the app through the flatpak uninstall -delete ——data command, and then reinstalling it, the problem still occurs.

**Comment by lil5** [comment]
> > @9thdude That sounds like an application issue, please pass this on to the Synology team.
> 
> 
> 
> After deleting the app through the flatpak uninstall -delete ——data command, and then reinstalling it, the problem still occurs.

@lisyclover  Did you delete the .SynologyDrive directory before reinstalling the flatpak as @9thdude said?
